apiVersion: v1
kind: ConfigMap
metadata:
  name: migrate-config
data:
  000001_create_urls_table.down.sql: DROP TABLE IF EXISTS urls;
  000001_create_urls_table.up.sql: |-
    CREATE TABLE IF NOT EXISTS urls (
        id bigserial PRIMARY KEY,
        shortKey text NOT NULL,
        longURL text NOT NULL
    );
