apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  datasource.yml: |-
    apiVersion: 1

    datasource:
      - name: Prometheus
        type: prometheus
        url: http://prometheus:9090
        isDefault: true
        access: proxy
        editable: true
