apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: migrate
        image: migrate/migrate
        command: ["migrate",  "--path", "/migrations", "--database", "postgres://urlshortening:pa55word@my-db/urlshortening?sslmode=disable", "up"]
        volumeMounts:
          - name: config-vol
            mountPath: /migrations
      restartPolicy: OnFailure
      volumes: 
        - name: config-vol
          configMap:
            name: migrate-config 
