apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  type: LoadBalancer
  selector:
    app: jaeger
  ports:
  - name: ui
    port: 16686
    targetPort: 16686
  - name: traces
    port: 4318
    targetPort: 4318
